//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavilionsEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.rents = new HashSet<rent>();
        }
    
        public int id_employee { get; set; }
        public string employee_surname { get; set; }
        public string employee_name { get; set; }
        public string employee_middlename { get; set; }
        public string employee_login { get; set; }
        public string employee_password { get; set; }
        public int id_role { get; set; }
        public string telephone { get; set; }
        public string sex { get; set; }
        public byte[] employee_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rent> rents { get; set; }
        public virtual role role { get; set; }
    }
}
