//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavilionsEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pavilion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pavilion()
        {
            this.rents = new HashSet<rent>();
        }
    
        public string id_pavilion { get; set; }
        public int id_shopping_center { get; set; }
        public int pavilion_floor { get; set; }
        public int pavilion_status { get; set; }
        public decimal pavilion_square { get; set; }
        public decimal cost_per_square_meter { get; set; }
        public decimal value_added_factor { get; set; }
    
        public virtual pavilionStatus pavilionStatus { get; set; }
        public virtual shopping_center shopping_center { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rent> rents { get; set; }
    }
}
