//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PavilionsEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shopping_center
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shopping_center()
        {
            this.pavilions = new HashSet<pavilion>();
        }
    
        public int id_shopping_center { get; set; }
        public string shopping_center_name { get; set; }
        public int id_status { get; set; }
        public int pavilions_quantity { get; set; }
        public string city { get; set; }
        public decimal cost { get; set; }
        public decimal value_added_factor { get; set; }
        public int number_of_storeys { get; set; }
        public byte[] shopping_center_image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pavilion> pavilions { get; set; }
        public virtual status status { get; set; }
    }
}
